mongodb:
  connection_string: "mongodb+srv://sofianelkwahi1937:A2TnYcfoed4GSmy0@cluster0.prykgrv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  database_name: "winedata"
  collection_name: "datasets_wine"

artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  raw_data_path: artifacts/data_ingestion/raw_data.csv

data_validation:
  root_dir: artifacts/data_validation
  raw_data_path: artifacts/data_ingestion/raw_data.csv
  validated_data_path: artifacts/data_validation/validated_data.csv
  status_file: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/raw_data.csv
  transformed_data_path: artifacts/data_transformation/transformed.csv
  preprocessor_path: artifacts/data_transformation/preprocessor.pkl

model_trainer:
  root_dir: artifacts/model_trainer
  transformed_data_path: artifacts/data_transformation/transformed.csv
  train_data_path: artifacts/model_trainer/train.csv
  test_data_path: artifacts/model_trainer/test.csv
  model_path: artifacts/model_trainer/model.joblib
  target_column: quality

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/model_trainer/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_path: artifacts/model_evaluation/metrics.json
  target_column: quality